### PR TITLE
Small cleanups: dead code removal and avoid string copies

### PR DESCRIPTION
**Pull request by shimpe**
Some more cleanups/fixes for inefficiencies I noticed while looking through the code.

### CODE REVIEW

**Comment by shimpe** [comment]
Feel free to let me know if you prefer a different code layout.

**Comment by abrolag** [comment]
Hi,
Thanks for all of these adjustments and corrections.
However we are on V1.7.1 rc1 and there are far too many for a thorough test before release, so I'll ask you to hang on, and I'll pull them into master immediately afterwards.
This should be between 1 or 2 weeks, depending on how quickly I can get all the documentation updated.

**Comment by shimpe** [comment]
Sure, no problem! 

Is there a list of bugs/TODOs/plans for the future as I was hoping to make myself a bit more useful once in a while. I can also come up with proposals myself if you prefer, but I don't want to act too intrusive if that makes sense.

**Comment by abrolag** [comment]
On Mon, 13 Apr 2020 06:00:51 -0700
shiihs <notifications@github.com> wrote:

>Sure, no problem! 
>
>Is there a list of bugs/TODOs/plans for the future as I was hoping to make myself a bit more useful once in a while. I can also come up with proposals myself if you prefer, but I don't want to act too intrusive if that makes sense.
>
>

Sorry to be slow getting back to you. Always appreciate any help.

If you check in the 'dev_notes' directory, there is a ToDo.txt list there (that
never seems to get shorter). There are also various other scraps of info.

I've just updated these with the latest commit along with some other files in
the 'doc' directory.

If you have other ideas of your own, if they are not too technical, the user
list would be the best place for them so other people can have a look - we do
try to be as inclusive as practical - otherwise, look at the areas the other
devs seem to have an interest in. It up to you if you want to put your heads
together or work separately of course. 

Hopefully V 1.7.1 will be done on Monday, then it's back to work :)

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Unfortunately this is now showing conflicts. Can you wait until I've merged in Kristian's work (which has no conflicts) then rebase your work on master again?

**Comment by shimpe** [comment]
Sure, no problem.

**Comment by shimpe** [comment]
please wait with merging until i've had some time to test out my conflict resolution

**Comment by shimpe** [comment]
this should be ok to merge

**Comment by abrolag** [comment]
OK, in now

**Pull request merged**
