### PR TITLE
Typos (relase -> release)

### PR DESCRIPTION
**Pull request by trebmuh**
Note that I didn't tested a build of it. Just fixed the typos within the github web interface.
Hope that helps.

### CODE REVIEW

**Comment by abrolag** [comment]
Hi Oliver,
Thanks for this. It won't go in the release now as that's out there, and I
never change a release except for serious bugs. However, once the dust has
settled, I'll pull it into the current master. I don't usually bother with
spelling errors in the code - the compiler won't care, and it's very easy to
end up duplicating a variable name!
For future reference, please always check code as much as possible before making
it available.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
I would add that your patch didn't catch all of these.

**Comment by trebmuh** [comment]
Hey mate, that's **your** code, and then **your** spelling mistakes. I found some, and reported those here to you in the hope that contributing to Yoshimi could be useful. But given the tone of your 2 answers here, I'm not 100% convinced that it's worth using my time for that... anyway, thanks for merging.

**Comment by dbtx** [comment]
2837457 didn't build because a few changed symbols weren't changed _everywhere_. It's almost always good to 'make clean all' before commit, or if you're dealing with CMake bits, 'rm -rf your_build_dir/*' and start over every time. That one helped me take the wrong idea from a cached value, just the other day-- so now my .bashrc has
`alias yoconfig='cmake ../yosh-upstream/src/ -DCMAKE_BUILD_TYPE="Release" -DBuildForAMD_X86_64=1 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_INSTALL_PREFIX="/usr"'  `
for skipping ccmake entirely ;)

**Pull request merged**
