### PR TITLE
Fix system effect volume having no effect.

### PR DESCRIPTION
**Pull request by kramlie**
The call to advance the value was missing.

Signed-off-by: Kristian Amlie <kristian@amlie.name>

### CODE REVIEW

**Comment by kramlie** [comment]
@abrolag: Here you go!

Btw, can you confirm that the Pan knob in System effects is wired opposite of what it should be? Left is right, and right is left, at least in the distortion effect.

**Comment by abrolag** [comment]
Seems to be right for Reverb but takes a *very* long time to change sides :)
Not availalbe for EQ.
OK for the rest - depending on settings.

**Comment by abrolag** [comment]
On Sat, 25 Sep 2021 07:26:40 -0700
kramlie ***@***.***> wrote:

***@***.***: Here you go!
>
>Btw, can you confirm that the Pan knob in System effects is wired opposite of what it should be? Left is right, and right is left, at least in the distortion effect.


Thanks for getting on to this so quickly.

Pan seems OK here, but it is *very* slow changing sides on reverb.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by kramlie** [comment]
> Pan seems OK here, but it is *very* slow changing sides on reverb.

Oh, now it's ok. What happened..? I must have crossed the wires in Jack or something. All good!

**Pull request merged**
